consul:
- instanceName: "prod"
  instanceURL: "https://prod.example.io"
  backup:
  - file:
      cron: "1 m"
      path: "backup/consul"
      exclude:
      - "/leader/.+"
      cleanPolicy: "2 m"
- instanceName: "test"
  instanceURL: "https://prod.example.io"
  backup:
  - file:
      cron: "1 m"
      path: "backup/consul"
      exclude:
      - "/leader/.+"
      cleanPolicy: "2 m"